#cloud-config

hostname: mininet-example
timezone: Europe/London

package_update: true
package_upgrade: true

packages:
  - git
  - curl
  - build-essential
  - python3
  - python3-pip
  - python3.10-venv
  - pkg-config
  - libssl-dev
  - net-tools
  - iproute2
  - tcpdump
  - openvswitch-switch
  - traceroute

runcmd:
  # Rust
  - su - ubuntu -c "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y"
  - echo 'source $HOME/.cargo/env' >> /home/ubuntu/.bashrc

  # Paris Traceroute
  - apt update
  - apt upgrade -y
  - apt install -y autoconf build-essential git libtool
  - mkdir -p /home/ubuntu/git
  - cd /home/ubuntu/git
  - git clone https://github.com/libparistraceroute/libparistraceroute.git
  - cd /home/ubuntu/git/libparistraceroute
  - mkdir -p m4
  - ./autogen.sh
  - ./configure
  - make -j2
  - make install
  - ldconfig

  # Clone Glasgow Traceroute
  - cd /home/ubuntu/git
  - git clone https://gitlab.cis.strath.ac.uk/rnb22136/glasgow-traceroute.git

  # Fix ownership
  - chown -R ubuntu:ubuntu /home/ubuntu/git

