frr version 9.1-MyOwnFRRVersion
frr defaults traditional
hostname vm-e
log syslog informational
ip forwarding
no ipv6 forwarding
service integrated-vtysh-config
!
router ospf
 ospf router-id 10.106.0.2
 network 10.106.0.0/24 area 0.0.0.0
 network 10.110.0.0/24 area 0.0.0.0
 network 10.107.0.0/24 area 0.0.0.0
exit
!
