frr version 9.1-MyOwnFRRVersion
frr defaults traditional
hostname vm-d
log syslog informational
ip forwarding
no ipv6 forwarding
service integrated-vtysh-config
!
router ospf
 ospf router-id 10.105.0.2
 network 10.105.0.0/24 area 0.0.0.0
 network 10.109.0.0/24 area 0.0.0.0
exit
!
